// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7KvsD0mrs9oqZDTRkSohpg0PFg8nZy0',
    appId: '1:918893539054:web:4cc35c603bf90c56010dff',
    messagingSenderId: '918893539054',
    projectId: 'rayye-4de2f',
    authDomain: 'rayye-4de2f.firebaseapp.com',
    storageBucket: 'rayye-4de2f.firebasestorage.app',
    measurementId: 'G-6QXKWQ8DLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9M7tsWXMGKd6MJ5YyWPLTaQF0r4PGEY',
    appId: '1:918893539054:android:a9c687a3753201f6010dff',
    messagingSenderId: '918893539054',
    projectId: 'rayye-4de2f',
    storageBucket: 'rayye-4de2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzwJl-KO7NtyUqD11kMrwR2TfI6J98bZQ',
    appId: '1:918893539054:ios:f3b205955ac672ca010dff',
    messagingSenderId: '918893539054',
    projectId: 'rayye-4de2f',
    storageBucket: 'rayye-4de2f.firebasestorage.app',
    iosBundleId: 'com.example.rayye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzwJl-KO7NtyUqD11kMrwR2TfI6J98bZQ',
    appId: '1:918893539054:ios:f3b205955ac672ca010dff',
    messagingSenderId: '918893539054',
    projectId: 'rayye-4de2f',
    storageBucket: 'rayye-4de2f.firebasestorage.app',
    iosBundleId: 'com.example.rayye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp7KvsD0mrs9oqZDTRkSohpg0PFg8nZy0',
    appId: '1:918893539054:web:64a05e1812e80911010dff',
    messagingSenderId: '918893539054',
    projectId: 'rayye-4de2f',
    authDomain: 'rayye-4de2f.firebaseapp.com',
    storageBucket: 'rayye-4de2f.firebasestorage.app',
    measurementId: 'G-PR9KRCP4WP',
  );
}
